name: Waypoint
main: com.zakrzu.waypoints.WaypointsPlugin
version: 1.2.1
api-version: 1.19
author: ZAKRZU
commands:
   waypoint:
      description: Gives ability to save waypoints
      usage: /<command>
      aliases: wp
      permission: waypoints.waypoint